version: "3.10"
services:
  app:
    build: .
    volumes: 
     - .:/django
    ports:
     - 8000:8000
    image: ez-app-reviewer-repository:latest
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000