version: '2.1'

orbs:
  aws-ecr: circleci/aws-ecr@8.1
  aws-ecs: circleci/aws-ecs@3.2

workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: "${AWS_RESOURCE_NAME_PREFIX}-repository"
          tag: 'latest'
          
      - aws-ecs/deploy-service-update:
           requires:
             - aws-ecr/build-and-push-image
           cluster: '${MY_APP_PREFIX}-cluster'
           family: '${MY_APP_PREFIX}-definition'
           service-name: '${MY_APP_PREFIX}-service'
           container-image-name-updates: "container=${AWS_RESOURCE_NAME_PREFIX}-container,image-and-tag=${AWS_ECR_REGISTRY_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${AWS_RESOURCE_NAME_PREFIX}-repository:latest"